server:
  port: 8103

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

spring:
  application:
    name: DEPARTMENT_SERVICE
  config:
    import: optional:configserver:http://localhost:8104

management:
  tracing:
    sampling:
      probability: 1.0