server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

spring:
  application:
    name: MEDICAL_SERVICE
  config:
    import: optional:configserver:http://localhost:8104 # Fetch config from Config Server

management:
  tracing:
    sampling:
      probability: 1.0