server:
  port: 8102

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
    enabled: true

spring:
  application:
    name: PATIENT_SERVICE
  config:
    import: optional:configserver:http://localhost:8104

management:
  tracing:
    sampling:
      probability: 1.0