server:
  port: 8104

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MuthomiGuantai/Jenkins_Test
          search-paths: Config_Server
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0